### ISSUE TITLE
"Enabled" option not working (warmer not firing)

### ISSUE THREAD

**Issue by individual11** [FidelLimited/serverless-plugin-warmup#100]
I know I 100% setup something wrong, but cannot figure it out for the life of me. Here is my YML

```
service: policy

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${opt:stage, self:provider.stage}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  warmup:
    enabled: true
    schedule: rate(1 minutes)
    prewarm: true

functions:
  withCustomer:
    handler: handler.withCustomer
    events:
      - http:
          path: /withCustomer
          method: POST
          cors: true
          warmup: true

```
When I deploy, I immediately see `Serverless: WarmUP: no lambda to warm` and at the end, I get the following:
```
functions:
  withCustomer: policy-staging-withCustomer
Serverless: WarmUP: Pre-warming up your functions
Serverless: WarmUp: Error while pre-warming functions
```

I check the logs, but can't see anything when I search for "warm" or any tags I've tried as well. I know I'm doing something dumb, but can't see it.

**Comment by trantien489** [comment]
Hello,
I had same issue.
This is my way which I reach the warm up:
 - remove 'enabled: true' in 'custom'.
 - Add 'warmup: true' with same level with 'handler' or 'events' in  each function which you want to warm.

**Comment by juanjoDiaz** [comment]
Hi guys,

There are a couple of problems:

1. Releases are blocked by the lack of maintainer (see #101) so the code in NPm doesn't match the latest code in GitHub. In short, the `enabled` option isn't even released. Until that's released you can use the `default` option instead as shown at https://www.npmjs.com/package/serverless-plugin-warmup#setup (once we release you should go back to `enabled`).
In general, you should use the instructions from NPM and not from GitHub (at the same time we should do a better job to keep GitHub and NPM in sync).
2. `warmup: true` at the function level is incorrectly indented. YML works based on indentation. In your code sample it's inside the `http` object which inside the `events ` array. It should be at the inside the function `withCustomer` i.e.:
```yml
functions:
  withCustomer:
    handler: handler.withCustomer
    events:
      - http:
          path: /withCustomer
          method: POST
          cors: true
    warmup: true
```
