### ISSUE TITLE
Unable to specify warmup for specified stage

### ISSUE THREAD

**Issue by drexler** [FidelLimited/serverless-plugin-warmup#103]
Serverless.yml

```
provider:
  stage: ${file(${opt:variables}):stage}
  name: aws

  #other configurations & functions 

custom:
  warmup:
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
  enabled:
    - production
```

The lambdas are deployed under different accounts - stages - and there's the need to restrict warming of them to one tier. Using the above configuration fails. It might be possibly related to #100.

**Comment by juanjoDiaz** [comment]
This is partially a duplicated of #100. Please read the comment there.

The problem is caused by the lack of maintainer blocking the releases (#101) 

In short, until the next release, change `enabled` by `default` 🙂 
Also, the indentation is incorrect.
```yml
custom:
  warmup:
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
    default:
      - production
```
