### ISSUE TITLE
Not able to make warmup a dictionary in the function definition

### ISSUE THREAD

**Issue by bhechinger** [FidelLimited/serverless-plugin-warmup#105]
In my global settings I have:

```
custom:
  warmup:
    enabled: true
    schedule: 'cron(0/5 * * * ? *)'
    concurrency: 20
```

If I set nothing in my function definition it never sets up WarmUp:

`Serverless: WarmUP: no lambda to warm`

If I add this to my function:

```
functions:
  AuthServer:
    warmup:
      enabled: true
```

I still get the message about no lambda to warm.

If I change it to:

```
functions:
  AuthServer:
    warmup: true
 ```

It then works as expected:

`Serverless: WarmUP: setting 1 lambdas to be warm`

How can I override global settings if I'm unable to use the dictionary format in the functions?
