### ISSUE TITLE
Support overriding packaging options

### ISSUE THREAD

**Issue by johndww** [FidelLimited/serverless-plugin-warmup#135]
In my project, we use package level include/excludes that aren't in the .serverless directory:
```
package:
  exclude:
    - ./**
    - '!../../../bin/service1/**'
    - '!../../../bin/service2/lambda'
```

because of this, the warmup plugin is creating an additional zip file that includes all of our lambdas. (30+ lambdas which doubles the data we have to upload to s3 during deploy).

The proposed fix is to allow overriding the exclude (which is currently hardcoded as ['**'].

```
custom:
  warmup:
    excludes:
      - ./**
      - ../../../bin/service1/**
      - ../../../bin/service2/lambda
```
