### ISSUE TITLE
Concurrency higher than 1

### ISSUE THREAD

**Issue by btmdave** [FidelLimited/serverless-plugin-warmup#150]
Hello,

I have `concurrency` set to `1` (have tried with default too), but it seems the concurrency is quite a bit higher, averaging around 8 and then some spikes, the only thing running here was warmup and a few random dev requests, so no traffic load.

<img width="1020" alt="Screenshot 2019-05-09 13 02 57" src="https://user-images.githubusercontent.com/28645/57472235-f7b57c00-725a-11e9-933f-aeb68c17f19f.png">

Any idea what might be causing this to have a higher concurrency level?  This is the config (had updated from 10 minutes to 15) and fyi is running in a VPC.

```
  warmup:
    enabled: true
    timeout: 30
    events:
      - schedule: rate(15 minutes)
    prewarm: true
    memorySize: 1024
    concurrency: 1
```

Thank you!
