### ISSUE TITLE
Is there a way to manually set SERVERLESS_ALIAS?

### ISSUE THREAD

**Issue by abadyan-vonage** [FidelLimited/serverless-plugin-warmup#161]
I am not using the sls alias plugin, but am deploying to a fixed alias (using this for serverless-plugin-canary-deployments).
How can I get the warmup plugin to use that alias? Ideally, this would be a setting on the plugin itself, or it would work with the canary plugin to figure that out.
Setting SERVERLESS_ALIAS on the provider level didn't work.

**Comment by juanjoDiaz** [comment]
Hi @abadyan-vonage ,

What do you mean with `Setting SERVERLESS_ALIAS on the provider level`?

Setting an environment variable called SERVERLESS_ALIAS should work
(see https://github.com/FidelLimited/serverless-plugin-warmup/blob/master/src/index.js#L327)

So something like `SERVERLESS_ALIAS=my_alias sls deploy` should work. Wasn't that the case?

**Comment by abadyan-vonage** [comment]
I tried setting the env var as part of the serverless.yml. I don't have direct access to env vars of the warmup lambda, so tried doing on the provider level:
```
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
     ...
  vpc:
     ...
  environment:
    SERVERLESS_ALIAS: myAlias
```

**Comment by juanjoDiaz** [comment]
That's not how you set the alias in serverles.
The environment field in the provider section contains the environment variables that will be passed to your lambdas, not the ones used for deployment.
You need to have the `SERVERLESS_ALIAS` variable set in your machine from where you run the serverless commands.

So you have to options:
1. `export SERVERLESS_ALIAS=my_alias` so the alias env var is set on the machine
2. `SERVERLESS_ALIAS=my_alias sls deploy` so the alias env var is set when the serverless command is run.

Let me know if that helps.

**Comment by abadyan-vonage** [comment]
@juanjoDiaz So setting the variable in the `SERVERLESS_ALIAS=my_alias sls deploy` form did make the warmup plugin warmup the correct alias during deployment (using `prewarm: true`) but the warmup lambda still doesn't get it as an env var leading to all consequent calls to still go to $LATEST.

**Comment by juanjoDiaz** [comment]
Sorry for the delay.

 4.6.3-rc.1 should fix this issue so the env variable injected by the sls alias plugin is automatically used by the warmup function and the prewarming without the need of using a local env variable or adding it to the serverless.yaml file.

Could you try and let me know?

**Comment by abadyan-vonage** [comment]
@juanjoDiaz thanks for the fix!
I am not using the alias plugin so would like to just pass in the env var manually. Where should it be defined with the new change you have made?

**Comment by juanjoDiaz** [comment]
In an env variable in serverless.yaml.
You can use the global environment setting so it's passed to all lambdas as you did on https://github.com/FidelLimited/serverless-plugin-warmup/issues/161#issuecomment-503461441.
Or if you want to pass it only to the plugin you can do:
```yaml
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
     ...
  vpc:
     ...
  custom:
    warmup:
      environment:
        SERVERLESS_ALIAS: myAlias
```
