### ISSUE TITLE
Unable to import module '_warmup/index'

### ISSUE THREAD

**Issue by TrentBartlem** [FidelLimited/serverless-plugin-warmup#18]
Hi. So I installed the plugin: (serverless-plugin-warmup@3.0.0-rc.1 for sls@1.15.3)

using
```
plugins:
  - serverless-plugin-warmup

custom:
  warmup:
    prewarm: true
    schedule: 'rate(10 minutes)'

provider:
  # ...  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*
  # ...
```

* deployment works
* lambda is created and named {service}-{environment}warmup-plugin (not the same as README.md states, but close enough)
* cloudwatch timer is created successfully
* When the warmup lambda is triggered, it fails with various flavours of

```
Unable to import module '_warmup/index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```
None of the other functions in my project are Node, so I'm not sure whether there's a step missing from the setup that's causing this.
