### ISSUE TITLE
No warmers generated for `prod` stage

### ISSUE THREAD

**Issue by Phebonacci** [FidelLimited/serverless-plugin-warmup#184]
Thanks for this great plugin! I would like to ask for your help with an issue we're encountering.
We're using the plugin for one of our projects and we've set the configuration as follows:

**serverless.yml**
```
...
# Warmed up env
  warmupEnabledEnv:
    - prod
    - uat # enabled only when necessary, like for testing purposes
  # Configuration for warmup
  warmup:
    name: ${self:service}-${opt:stage}-lambda-warmer
    enabled: false # we only warm up the relevant ones. pls see service.yml per route
    prewarm: true
    timeout: 20
    events:
      - schedule: 'cron(0/5 19-15 * * ? *)' # everyday, 7am NZT to 11pm Perth time, 20hrs uptime for warm up with 5mins interval
...
```

**xx/service.yml** (we separate the configuration for our lambda functions/handlers)
```
...
setMobile:
    warmup:
      enabled: ${self:custom.warmupEnabledEnv}
    handler: ${self:custom.dist}/users.setMobile
...
```

As shown on the serverless.yml file, we've enabled warm up on uat and prod stages. Warm up is working well on uat, but on prod, the warmers don't even get generated. Just wanted to ask if there's something wrong with our configuration. Thanks!
