### ISSUE TITLE
Add possibility to use Role Import as the value for role attribute

### ISSUE THREAD

**Issue by azhurtbayev-klikatech** [FidelLimited/serverless-plugin-warmup#187]
https://github.com/FidelLimited/serverless-plugin-warmup/blob/d4b2bd91c766b2f51b880e545d990dee768e6150/src/index.js#L159

**Comment by juanjoDiaz** [comment]
Hi @azhurtbayev-klikatech ,

Can you elaborate a bit on what exactly are you asking for?
I don't really understand.

**Comment by azhurtbayev-klikatech** [comment]
Hello @juanjoDiaz ,

At the moment, the only way to specify a role for the Warmup function is to specify it as string value.
I use serverless additional stacks plugin to define all project roles within a separate stack.

Now, I try to define a role for warmup function like this:
```
custom:
  warmup:
    name: ${{self:custom.appName}}-warmup
    role: {"Fn::ImportValue": "${{self:custom.appName}}-warmup-role-arn"}
```
In this case, I cannot apply this role to the function, because it is not of a string type.
