### ISSUE TITLE
Service level package config is added to warmup function package config by default

### ISSUE THREAD

**Issue by chearmstrong** [FidelLimited/serverless-plugin-warmup#191]
We're creating a build which is output to `dist` in our project root.

In `serverless.yml` we have this.

```yml
package
  individually: true
  exclude:
    - ./**
  include:
    - dist/index.js
```

This is working fine for the main function. However, for the `warmup` lambda, it's including the `dist` code. I've tried adding a `package` to `custom.warmup` but I can't get it to be excluded.

I've tried lots of variations, and this is what I _currently_ have.

```yml
warmup:
  name: alexa-custom-warmup-${opt:stage, 'dev'}
  cleanFolder: true
  prewarm: true
  package:
    individually: true
    exclude:
      - ./**
    include:
      - _warmup/index.js
```

Any ideas?

**Comment by juanjoDiaz** [comment]
Hi @chearmstrong ,

Sorry for the delay in answering.
Your configuration is correct and this looks like a bug indeed. I'll look into it.

Are you using the latest version of the plugin?

**Comment by bfelbo** [comment]
FYI, we're facing the same issue with the latest version installed through npm.

**Comment by chearmstrong** [comment]
Yeah. It’s the latest version. Thanks.

**Comment by juanjoDiaz** [comment]
Sorry for the delay answer. Christmas holidays got on the way.

Are you setting:
```yaml
package:
  individually: true
  exclude:
    - ./**
  include:
    - dist/index.js
```

at your function level? Or at the service level?
Can you share the whole config? (of course, you can obscure the names and other sensitive stuff)

I suspect that you are setting it at the package level. Which is automatically inherited by the warmup lambda unless you override it at the warmup configuration (as you already figured out).

Maybe this was a questionable decision and the service-level package configuration shouldn't be inherited. But that would be a breaking change that would require a major version change.

I'll consider it for 5.0. 😄

**Comment by juanjoDiaz** [comment]
Almost a year later but I'm looking back at this.

The issue seems to be in the serverless framework itself prioritizing includes over excludes... (see https://github.com/serverless/serverless/issues/8093)

For now the workaround is to force the exclusions but using includes like:
```yaml
warmup:
  name: alexa-custom-warmup-${opt:stage, 'dev'}
  cleanFolder: true
  prewarm: true
  package:
    individually: true
    include:
      - !dist/index.js
      - _warmup/index.js
```

I'll be releasing v5 at some point and making excluding the top level includes the default.
