### ISSUE TITLE
ClientContext json exception when we have json input as payload

### ISSUE THREAD

**Issue by jayasai470** [FidelLimited/serverless-plugin-warmup#207]
I have a json payload of api gateway request for one of my java functions
this is a seperate file http-event.json in my serverless stack
```yaml
warmup:
    enabled: false
    cleanFolder: false
    memorySize: 256
    name:  ${self:custom.stageOption}-warmup
    timeout: 20
    prewarm: true
    payload: ${file(http-event.json)}
```

function produces payload with json string, but when invoking the function with client context 
below param is not working as it produces a JSON and when the target function gets invoked with the context it tries to json parse the string and getting an exception in target lambda
```js
const params = {
      ClientContext: Buffer.from(`{"custom":${func.config.payload}}`).toString('base64'),
      FunctionName: func.name,
      InvocationType: "RequestResponse",
      LogType: "None",
      Qualifier: process.env.SERVERLESS_ALIAS || "$LATEST",
      Payload: func.config.payload
    };
```
