### ISSUE TITLE
Support concurrency with different schedules

### ISSUE THREAD

**Issue by singla96** [FidelLimited/serverless-plugin-warmup#213]
Current: Currently i can only warm n number of instances with any scheduled event.

Use Case: Mon-Fri will be normal traffic. on weekends i expect higher traffic (or may be some specific hours everyday). I would like to warm 4 times more containers than usual in this case.

Expected: some configuration like 
events:
      - schedule: 'cron(0/15 1-5 ? * MON-SUN *)'
              - concurrency: 10
      - schedule: 'cron(0/15 6-8 ? * MON-SUN *)'
              - concurrency: 20

would eliminate this issue and we can handle predicted spikes with this.

**Comment by juanjoDiaz** [comment]
Hi @singla96 ,

This sounds like a reasonable feature to have and I'd be very happy to have it in the plugin.

I like how the current parameters (`event`, `payload`, etc.) match the parameters of a standard lambda and they are well defined and cascaded from the service to the lambdas.
I wouldn't want to change that by having an `event` that also takes a `concurrency`. It sounds messy. What if you also want different payloads for different events?

So my proposal would be named warmers.

```yaml
custom:
  warmup:
    memorySize: 256
    role: myCustRole0
    tags:
      Project: foo
      Owner: bar 
    # This is the new option
    named:
      weekly-warmer:
        enabled: true
        events:
          - schedule: 'cron(0/15 1-5 ? * MON-SUN *)'
        concurrency: 10
      weekend-warmer:
        enabled: true
        events:
          - schedule: 'cron(0/15 6-8 ? * MON-SUN *)'
        concurrency: 20
```

The options defined at the warmup level are cascaded to the named warmers.
If the name property is not defined, then it will be considered as a single named warmer called `default`.

You can override the named warmers at the function level by using the same name.

Wdyt?

**Comment by singla96** [comment]
hmm . agree with you.  your approach has wider use case scenario covered. Also any parameters mentioned outside will apply to all named warmers.

`
custom:
  warmup:
    enabled: true
    memorySize: 256
    role: myCustRole0
    tags:
      Project: foo
      Owner: bar 
    # This is the new option
    concurrency: 10
    named:
      weekly-warmer:
        events:
          - schedule: 'cron(0/15 1-5 ? * MON-SUN *)'
      weekend-warmer:
        events:
          - schedule: 'cron(0/15 6-8 ? * MON-SUN *)'
        concurrency: 20
      some-other-warmer:
        enabled: false
        events:
          - schedule: 'cron(0/15 6-8 ? * MON-SUN *)'
`

here weekly-warmer and some-other -warmer should have concurrency 10

**Comment by juanjoDiaz** [comment]
Will be released as part of version 5

**Comment by juanjoDiaz** [comment]
This took way to long but v5 is finally out.

**Comment by AnushriGulhane** [comment]
Hi @juanjoDiaz ,
I am not getting how to attach multiple warmer function to single lambda function in a service.
for example
1.hello: //lambda function
     warmup:
            weekly-warmer: true
I have 3 warmer functions and it is getting applied to all 5 lambda functions.
how to enable it for 1 lambda function? as I want different concurrencies between three different time slots

**Comment by juanjoDiaz** [comment]
Hi @anushri2512 ,

`weekly-warmer: true` is using the old shorthand notation which has been deprecated in v5.

You need to use the `enabled` property
```yaml
warmup:
  weekly-warmer:
    enabled: true
```

**Comment by anushri2512** [comment]
Getting below error after using enabled property at function 

Error: WarmUp: Invalid function-level warmup configuration (highConcurrencyWarmer) in function. Every warmer should be declared in the custom section.

I have  highConcurrencyWarmer in custom section

**Comment by juanjoDiaz** [comment]
Can you post your full yaml config (or at least the custom section and the function config) so I can take a look?

The error indicates that `highConcurrencyWarmer` is not declared.

It should be something like:

```yaml

custom:
  warmup:
    highConcurrencyWarmer:
      enabled: false
# ...

functions:
  myFunction:
    # ...
    warmup:
      highConcurrencyWarmer:
        enabled: true
```
