### ISSUE TITLE
Does this trigger authorizers attached to the lambda function?

### ISSUE THREAD

**Issue by reilg** [FidelLimited/serverless-plugin-warmup#221]
For example:

```yml
# serverless.yml
functions:
  auth: 
    handler: path/to/auth.js
  hello:
    warmup: 
      enabled: true
```
```js
// auth.js
module.exports.auth = (event, context, callback) => {
  if (event.source === 'serverless-plugin-wawrmup') {
    callback(null, 'Is warm')
  }
  ... auth logic
}
```

Would this kind of setup work?
