### ISSUE TITLE
Extend Serverless validation schema with the plugin options

### ISSUE THREAD

**Issue by gruckionvit** [FidelLimited/serverless-plugin-warmup#222]
I am using the follow plugins;

```
plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-warmup
```

And have `warm` on my function.

```
functions:
  RestAPI:
    name: "${self:custom.myServiceName}"
    handler: lambda.handler
    memorySize: 128
    timeout: 30
    description: REST API
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
    warmup:
      enabled: true
    environment:
      NODE_ENV: ${self:custom.myStage}
```

Any ideas why this isn't working? It worked before. But now I get this warning in the console everytime I deploy.

```
Serverless: Configuration warning at 'functions.RestAPI': unrecognized property 'warmup'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: WarmUp: setting 1 lambdas to be warm
```
