### ISSUE TITLE
Handle multiple schedules?

### ISSUE THREAD

**Issue by TrentBartlem** [FidelLimited/serverless-plugin-warmup#28]
I know that this works:
```
custom:
  warmup:
    schedule: 'rate(10 minutes)'
```

but would it be possible to trigger from _multiple_ schedules?

e.g.

```
custom:
  warmup:
    schedule:
      - 'cron(0/10 11-13 ? * MON-FRI *)'
      - 'cron(0/10 17-20 ? * MON-SAT *)'
```
