### ISSUE TITLE
Enabling warmup only for a specific stage

### ISSUE THREAD

**Issue by jeanlamy** [FidelLimited/serverless-plugin-warmup#29]
Hi,

Not an issue so sorry for creating an issue. But I was wondering how can I use this plugin to enable warmup only for a specific stage (production for example).

**Comment by jeanlamy** [comment]
Just answering to myself. I think this can be done using the following
```
custom:
  warmupenabled:
    dev: false
    staging
    prod: true
myfunction:
  warmup: ${self:custom.warmupenabled.${opt:stage, self:provider.stage}}
```
