### ISSUE TITLE
 ENOENT: no such file or directory, open 'serverless-graphql-apollo/app-backend/.webpack/.serverless/warmUpPlugin.zip'

### ISSUE THREAD

**Issue by kristiankyvik** [FidelLimited/serverless-plugin-warmup#37]
Hi,
Firstly, thanks for making these plugin. I running into the following error when trying to deploy with the serverless-plugin-warmup enabled.

This is the error message:

```yarn run deploy-server-lambda-prod
yarn run v1.1.0
warning You are using Node "7.10.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ serverless --stage=production deploy
Serverless: WarmUP: setting 2 lambdas to be warm
Serverless: WarmUP: serverless-graphql-apollo-production-graphql
Serverless: WarmUP: serverless-graphql-apollo-production-graphiql
Serverless: Bundling with Webpack...
Time: 1578ms
           Asset     Size  Chunks             Chunk Names
      handler.js  7.32 kB       0  [emitted]  handler
_warmup/index.js  4.13 kB       1  [emitted]  _warmup/index
Serverless: Packing external modules: graphql@^0.10.5, apollo-server-lambda@1.1.2, babel-core@^6.17.0, babel-polyfill@^6.16.0, graphql-tools@^1.0.0, request@^2.83.0, request-promise@^4.2.2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  ENOENT: no such file or directory, open '/Users/kristiankyvik/code/serverless-graphql-apollo/app-backend/.webpack/.serverless/warmUpPlugin.zip'
```

This is my serverless.yml:

```
service: serverless-graphql-apollo

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    MLAB_API_KEY: ${file(./serverless.env.yml):${opt:stage}.MLAB_API_KEY}
    HOME: /tmp
    SLS_DEBUG: true

plugins:
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-webpack
  - serverless-delete-loggroups
  
custom:
  serverless-offline:
    port: 4000
    babelOptions:
      presets: ["es2015", "stage-2"]
  webpackIncludeModules: true

functions:
  graphql:
    handler: handler.graphqlHandler
    warmup: true
    events:
    - http:
        path: graphql
        method: post
        cors: true

  graphiql:
    handler: handler.graphiqlHandler
    warmup: true
    events:
    - http:
        path: graphiql
        method: get
        cors: true
```

And this is my webpack config:

```
const path = require('path');
// eslint-disable-next-line import/no-extraneous-dependencies
const nodeExternals = require('webpack-node-externals');
// eslint-disable-next-line import/no-extraneous-dependencies
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [{
      test: /\.js$/,
      use: [
        'imports-loader?graphql',
        {
          loader: 'babel-loader',
          options: {
            presets: ['es2015'],
          },
        },
      ],
    }],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
};
```

Please let me know if you guys any ideas of how I can fix this.
