### ISSUE TITLE
Hangs up on remove or deploy when changing .yaml

### ISSUE THREAD

**Issue by gideonairex** [FidelLimited/serverless-plugin-warmup#47]
I'am having problems when Im updating my .yaml for serverless-plugin-warmup.
```
...
plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    name: webhook-warmup-plugin
    prewarm: true
...
functions:
  webhook:
    handler: handler.webhook
    warmup: true
    events:
      - http:
          path: webhook
          method: get
```
Before adding that ```custom``` all are working. Then I tried to ```sls deploy``` but it hangs up. What I did is that I stopped the deploy then tried to ```sls remove```. Then it gave an error like
 
``` Stack:arn:aws:cloudformation:us-west-2:124176118271:stack/webhook-dev/5363ea00-11e5-11e8-a57b-50a68a0e32f2 is in UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated.```

This happened to me like twice when changing some config like the VPC or the custom.

Note:
Also the first time I encounter this problem I deleted my s3 bucket for my lambda then deleted the cloud formation. Your help is much appreciated. Thanks.
