### ISSUE TITLE
iamRoleStatements not allowing invocation

### ISSUE THREAD

**Issue by murtyjones** [FidelLimited/serverless-plugin-warmup#53]
I'm receiving the following error on every attempted invoke:

```
Warm Up Invoke Error: auth-service-dev-myFunctionName { AccessDeniedException: User: 
arn:aws:sts::[redacted]:assumed-role/auth-service-dev-us-east-1-lambdaRole/auth-service-
dev-warmup-plugin is not authorized to perform: lambda:InvokeFunction on resource: 
arn:aws:lambda:us-east-1:[redacted]:function:auth-service-dev-myFunctionName

```

My config looks like this:
```
custom:
  warmup:
    folderName: '_warmup' # Name of the folder created for the generated warmup
    cleanFolder: false
    memorySize: 128
    schedule: 'cron(0/5 14-4 ? * MON-SUN *)' # Run WarmUP every 5 minutes Mon-Sun between 8:00am and 10:55pm (UTC)
    timeout: 20
    prewarm: true # Run WarmUp immediately after a deployment
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
```

Is there something obvious I'm missing about setting up permissions for the warmup plugin?
