### ISSUE TITLE
How do I tell if it's working?

### ISSUE THREAD

**Issue by jascination** [FidelLimited/serverless-plugin-warmup#62]
Super basic question. I followed everything in the readme; set all of my functions to have `warmup: true`, `serverless-plugin-warmup` is in my `serverless.yml`'s plugins, as well as this definition:

```
  warmup:
    folderName: '_warmup' # Name of the folder created for the generated warmup 
    cleanFolder: false
    memorySize: 256
    name: 'make-them-pop'
    schedule: 'cron(0 0/1 * 1/1 * ? *)' # Run WarmUP every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
    timeout: 20
    prewarm: true # Run WarmUp immediately after a deployment
```

(trying to run it every minute locally for debugging purposes).

When I run my offline/local serverless project, I don't see any console logs relating to Warmup, so have no idea if/when the service is running. I _don't_ see a `_warmup` folder anywhere, so maybe this is a sign it's not working?

How can I test this plugin?
