### ISSUE TITLE
Feature Request : specify schedule by stages

### ISSUE THREAD

**Issue by T4ze** [FidelLimited/serverless-plugin-warmup#64]
Hi,

First of all, thanks for the plugin! There is currently a way to activate the warmup only on some stages and that's great. But it could be even nicer to be able to set a configuration per stages (for example if we want different `schedule` or `timeout`).

Thx,

**Comment by goncaloneves** [comment]
Hi @T4ze.

What I do is use Serverless variables with `--stage` command argument for different service settings per stage/region.

In your case, you would create a variable file for each stage with their unique `schedule` and `timeout` values and fetch those in warmup settings like:
```yaml
custom:
  stage: dev
  warmup:
    schedule: ${file(path/variables.${opt:stage}.json):warmupSchedule}
    timeout: ${file(path/variables.${opt:stage}.json):warmupTimeout}
```
More:
https://serverless.com/framework/docs/providers/aws/guide/variables/#variables

Considering this native solution, it would be bloat bringing this to the plugin.
