### ISSUE TITLE
Unnecessary error message when pre-warming

### ISSUE THREAD

**Issue by greg-manifold** [FidelLimited/serverless-plugin-warmup#90]
This is a relatively minor issue, but currently some unnecessary messages are displayed when setting pre-warm to true:

```
Serverless: WarmUP: Pre-warming up your functions
Serverless: WarmUp: Error while pre-warming functions
```

This error occurs if pre-warm is true, warmup: default is set to certain stages, and we're deploying to a stage not specified to be warmed. I.e. serverless.yml looks like this:

```
custom:  
  warmup:
     prewarm: true
     default:   
       - staging
       - prod
```
And then we deploy to `dev`.
