### ISSUE TITLE
Warming up all lambdas with custom.warmup.enable = true 

### ISSUE THREAD

**Issue by ibabicuy** [FidelLimited/serverless-plugin-warmup#92]
Im trying to configure two lambdas to warm up, but the plug in doesn't detect them, I'm getting:

Serverless: WarmUP: no lambda to warm
Serverless: Installing requirements of requirements.txt in .serverless...

with this configuration:

```yml
custom:
  stage: ${opt:stage, self:provider.stage}
  lambdaMetricsTableName: ${self:provider.stage}-lambda-metric
  tableThroughputs:
    prod: 50
    dev: 50
    default: 5
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  pythonRequirements:
    dockerizePip: non-linux
  warmup:
    enabled: false
    timeout: 20
    prewarm: true

functions:
  check-pax-availability:
    handler: src/check_availability.run
  check-pax-availability-intervals:
    handler: src/check_availability_SAT_rotation_interval.run
    memorySize: 1024
    warmup:
      enabled: true
      concurrency: 500
  check-available-times:
    handler: src/check_available_times.run
    memorySize: 1024
    warmup:
      enabled: true
      concurrency: 5
  auto-assign-tables:
    handler: src/auto_assign_tables.run
  layout-generation-unique-product:
    handler: src/layouts_generation_utils.run
```
