### ISSUE TITLE
Help Wanted: Facing cold start issue

### ISSUE THREAD

**Issue by ankkho** [FidelLimited/serverless-plugin-warmup#98]
I have implemented this plugin and still facing cold start issue. My event source is API Gateway.

> Note: I am using VPC, and by default lambda function within VPC are kept warm for 15 minutes.

Following is my `warmup` config:
```
  warmup:
    default: true
    folderName: '_warmup'
    cleanFolder: true
    memorySize: 128
    name: 'keep-function-warm'
    role: warmup-role
    timeout: 20
    prewarm: true
    concurrency: 5
```
How can I resolve this?
